/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarymanagementkiosk;

import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author CLARISSE
 */
public class LibrarianForgotPassword extends javax.swing.JFrame {

    /**
     * Creates new form Registration
     */
    public LibrarianForgotPassword() {
        initComponents();
        this.setLocationRelativeTo(null); //center screen
        
        
        Border emptyBorder = BorderFactory.createEmptyBorder();
        btn_save.setBorder(emptyBorder);
        btn_reset.setBorder(emptyBorder);
        btn_search.setBorder(emptyBorder);
        textfieldquestion.setBorder(emptyBorder);
        
        btn_save.setFocusPainted(false);
        btn_reset.setFocusPainted(false);
        btn_search.setFocusPainted(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblusername = new javax.swing.JLabel();
        textfieldusername = new javax.swing.JTextField();
        lblpassword = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        lblconfirmpass = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabelLogin = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelicon = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        back = new javax.swing.JLabel();
        jLabelLoida = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        lblconfirmpass1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_reset = new button.MyButton();
        btn_save = new button.MyButton();
        jLabel5 = new javax.swing.JLabel();
        lbl_u = new javax.swing.JLabel();
        lbl_p = new javax.swing.JLabel();
        lbl_cp = new javax.swing.JLabel();
        lbl_a = new javax.swing.JLabel();
        textfieldanswer = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btn_search = new button.MyButton();
        textfieldquestion = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblpassword1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(93, 70, 56), 5));

        lblusername.setFont(new java.awt.Font("Rockwell Condensed", 1, 18)); // NOI18N
        lblusername.setText("Username:");

        textfieldusername.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        textfieldusername.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(93, 70, 56)));
        textfieldusername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textfieldusernameMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                textfieldusernameMousePressed(evt);
            }
        });
        textfieldusername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textfieldusernameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textfieldusernameKeyTyped(evt);
            }
        });

        lblpassword.setFont(new java.awt.Font("Rockwell Condensed", 1, 18)); // NOI18N
        lblpassword.setText("Password:");

        jPasswordField1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPasswordField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(93, 70, 56)));
        jPasswordField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordField1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPasswordField1MousePressed(evt);
            }
        });
        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyTyped(evt);
            }
        });

        lblconfirmpass.setFont(new java.awt.Font("Rockwell Condensed", 1, 18)); // NOI18N
        lblconfirmpass.setText("Confirm Password:");

        jPasswordField2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPasswordField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(93, 70, 56)));
        jPasswordField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordField2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPasswordField2MousePressed(evt);
            }
        });
        jPasswordField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField2ActionPerformed(evt);
            }
        });
        jPasswordField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPasswordField2KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPasswordField2KeyTyped(evt);
            }
        });

        jLabelLogin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelLogin.setForeground(new java.awt.Color(12, 105, 169));
        jLabelLogin.setText("Sign in");
        jLabelLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLoginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelLoginMouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Remember your password?");

        jPanel2.setBackground(new java.awt.Color(64, 134, 176));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jLabelicon, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 287, -1, -1));
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 287, -1, -1));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymanagementkiosk/neweralogo.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 180, 173, -1));

        jPanel3.setBackground(new java.awt.Color(64, 134, 176));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymanagementkiosk/icons8-back-arrow-40.png"))); // NOI18N
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(700, 700, 700)
                .addComponent(back)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(back)
                .addGap(381, 381, 381))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        jLabelLoida.setFont(new java.awt.Font("Rockwell", 1, 36)); // NOI18N
        jLabelLoida.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLoida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymanagementkiosk/era2.png"))); // NOI18N
        jPanel2.add(jLabelLoida, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 360, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Library Management Kiosk ");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 390, -1, -1));

        jPanel21.setBackground(new java.awt.Color(151, 205, 205));
        jPanel21.setPreferredSize(new java.awt.Dimension(500, 25));

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 708, Short.MAX_VALUE)
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        lblconfirmpass1.setFont(new java.awt.Font("Rockwell Condensed", 1, 18)); // NOI18N
        lblconfirmpass1.setText("Answer:");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymanagementkiosk/forgot.png"))); // NOI18N

        btn_reset.setForeground(new java.awt.Color(255, 255, 255));
        btn_reset.setText("RESET");
        btn_reset.setBorderColor(new java.awt.Color(64, 134, 176));
        btn_reset.setColor(new java.awt.Color(64, 134, 176));
        btn_reset.setColorClick(new java.awt.Color(102, 153, 255));
        btn_reset.setColorOver(new java.awt.Color(64, 134, 176));
        btn_reset.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_reset.setRadius(30);
        btn_reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_resetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_resetMouseExited(evt);
            }
        });
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });

        btn_save.setText("SAVE");
        btn_save.setBorderColor(new java.awt.Color(64, 134, 176));
        btn_save.setColorClick(new java.awt.Color(102, 153, 255));
        btn_save.setColorOver(new java.awt.Color(64, 134, 176));
        btn_save.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_save.setRadius(30);
        btn_save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_saveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_saveMouseExited(evt);
            }
        });
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymanagementkiosk/fp.png"))); // NOI18N

        lbl_u.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_u.setForeground(new java.awt.Color(255, 0, 0));
        lbl_u.setText("*");

        lbl_p.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_p.setForeground(new java.awt.Color(255, 0, 0));
        lbl_p.setText("*");

        lbl_cp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_cp.setForeground(new java.awt.Color(255, 0, 0));
        lbl_cp.setText("*");

        lbl_a.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_a.setForeground(new java.awt.Color(255, 0, 0));
        lbl_a.setText("*");

        textfieldanswer.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        textfieldanswer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(93, 70, 56)));
        textfieldanswer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textfieldanswerMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                textfieldanswerMousePressed(evt);
            }
        });
        textfieldanswer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textfieldanswerKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textfieldanswerKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Forgot your password?");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel8.setText(" Don't worry! Resetting your password is easy. ");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel9.setText("Just type in the username you registered in ERANIAN.");

        btn_search.setForeground(new java.awt.Color(255, 255, 255));
        btn_search.setText("SEARCH");
        btn_search.setBorderColor(new java.awt.Color(64, 134, 176));
        btn_search.setColor(new java.awt.Color(64, 134, 176));
        btn_search.setColorClick(new java.awt.Color(102, 153, 255));
        btn_search.setColorOver(new java.awt.Color(64, 134, 176));
        btn_search.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_search.setRadius(30);
        btn_search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_searchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_searchMouseExited(evt);
            }
        });
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });

        textfieldquestion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblpassword1.setFont(new java.awt.Font("Rockwell Condensed", 1, 18)); // NOI18N
        lblpassword1.setText("Security Question:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblpassword1)
                .addContainerGap(257, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblpassword1)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(jLabel7))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jLabel8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jLabel9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(lblusername)
                        .addGap(4, 4, 4)
                        .addComponent(lbl_u))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(textfieldusername, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(btn_search, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(textfieldquestion, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(lblconfirmpass1)
                        .addGap(3, 3, 3)
                        .addComponent(lbl_a))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(textfieldanswer, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(lblpassword)
                        .addGap(7, 7, 7)
                        .addComponent(lbl_p)
                        .addGap(121, 121, 121)
                        .addComponent(lblconfirmpass)
                        .addGap(3, 3, 3)
                        .addComponent(lbl_cp))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(btn_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jLabel1)
                        .addGap(4, 4, 4)
                        .addComponent(jLabelLogin))))
            .addComponent(jPanel21, javax.swing.GroupLayout.DEFAULT_SIZE, 708, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel5)
                                .addGap(24, 24, 24)
                                .addComponent(jLabel7)))
                        .addGap(11, 11, 11)
                        .addComponent(jLabel8)
                        .addGap(1, 1, 1)
                        .addComponent(jLabel9)
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblusername)
                            .addComponent(lbl_u))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textfieldusername, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_search, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(textfieldquestion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblconfirmpass1)
                            .addComponent(lbl_a))
                        .addGap(8, 8, 8)
                        .addComponent(textfieldanswer, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblpassword)
                            .addComponent(lbl_p)
                            .addComponent(lblconfirmpass)
                            .addComponent(lbl_cp))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabelLogin))))
                .addGap(4, 4, 4)
                .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public boolean verifData() {
        if (textfieldusername.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Username is required", "Message", JOptionPane.ERROR_MESSAGE);
        } else if (jPasswordField1.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Password is required", "Message", JOptionPane.ERROR_MESSAGE);
        } else if (!String.valueOf(jPasswordField1.getPassword()).equals(String.valueOf(jPasswordField2.getPassword()))) {
            JOptionPane.showMessageDialog(null, "Password does not match", "Message", JOptionPane.ERROR_MESSAGE);
        } else if (textfieldquestion.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Security Question is required", "Message", JOptionPane.ERROR_MESSAGE);
        } else if (textfieldanswer.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Answer is required", "Message", JOptionPane.ERROR_MESSAGE);
            return false;
        } else {
            return true;
        }
        return false;
    }


    private void jLabelLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLoginMouseClicked
        LibrarianLogin log = new LibrarianLogin();
        log.setVisible(true);
        log.pack();
        log.setLocationRelativeTo(null);
        log.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabelLoginMouseClicked

    private void jPasswordField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField2ActionPerformed

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        Users user = new Users();
        user.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_backMouseClicked

    private void backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseEntered
        jPanel3.setBackground(new Color(7, 74, 114));
    }//GEN-LAST:event_backMouseEntered

    private void backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseExited
        jPanel3.setBackground(new Color(64, 134, 176));
    }//GEN-LAST:event_backMouseExited

    private void jLabelLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLoginMouseEntered
        jLabelLogin.setForeground(new Color(8, 14, 112));
    }//GEN-LAST:event_jLabelLoginMouseEntered

    private void jLabelLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLoginMouseExited
        jLabelLogin.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_jLabelLoginMouseExited

    private void textfieldusernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textfieldusernameMouseClicked

    }//GEN-LAST:event_textfieldusernameMouseClicked

    private void jPasswordField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField1MouseClicked

    }//GEN-LAST:event_jPasswordField1MouseClicked

    private void jPasswordField2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField2MouseClicked

    }//GEN-LAST:event_jPasswordField2MouseClicked

    private void textfieldusernameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textfieldusernameMousePressed
        Border a = BorderFactory.createLineBorder(new Color(64, 134, 176), 2);
        textfieldusername.setBorder(a);
        Border b = BorderFactory.createLineBorder(new Color(93, 70, 56), 1);
        
        jPasswordField1.setBorder(b);
        jPasswordField2.setBorder(b);
        //textfieldquestion.setBorder(b);
        textfieldanswer.setBorder(b);
    }//GEN-LAST:event_textfieldusernameMousePressed

    private void jPasswordField1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField1MousePressed
        Border a = BorderFactory.createLineBorder(new Color(64, 134, 176), 2);
        jPasswordField1.setBorder(a);
        Border b = BorderFactory.createLineBorder(new Color(93, 70, 56), 1);
        
        textfieldusername.setBorder(b);
        jPasswordField2.setBorder(b);
        //textfieldquestion.setBorder(b);
        textfieldanswer.setBorder(b);
    }//GEN-LAST:event_jPasswordField1MousePressed

    private void jPasswordField2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField2MousePressed
        Border a = BorderFactory.createLineBorder(new Color(64, 134, 176), 2);
        jPasswordField2.setBorder(a);
        Border b = BorderFactory.createLineBorder(new Color(93, 70, 56), 1);
        
        textfieldusername.setBorder(b);
        jPasswordField1.setBorder(b);
        //textfieldquestion.setBorder(b);
        textfieldanswer.setBorder(b);
    }//GEN-LAST:event_jPasswordField2MousePressed

    private void textfieldusernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textfieldusernameKeyTyped
        Border a = BorderFactory.createLineBorder(new Color(64, 134, 176), 2);
        textfieldusername.setBorder(a);
        Border b = BorderFactory.createLineBorder(new Color(93, 70, 56), 1);
        
        jPasswordField1.setBorder(b);
        jPasswordField2.setBorder(b);
        //textfieldquestion.setBorder(b);
        textfieldanswer.setBorder(b);
    }//GEN-LAST:event_textfieldusernameKeyTyped

    private void jPasswordField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyTyped
        Border a = BorderFactory.createLineBorder(new Color(64, 134, 176), 2);
        jPasswordField1.setBorder(a);
        Border b = BorderFactory.createLineBorder(new Color(93, 70, 56), 1);
        
        textfieldusername.setBorder(b);
        jPasswordField2.setBorder(b);
        //textfieldquestion.setBorder(b);
        textfieldanswer.setBorder(b);
    }//GEN-LAST:event_jPasswordField1KeyTyped

    private void jPasswordField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField2KeyTyped
        Border a = BorderFactory.createLineBorder(new Color(64, 134, 176), 2);
        jPasswordField2.setBorder(a);
        Border b = BorderFactory.createLineBorder(new Color(93, 70, 56), 1);
        
        textfieldusername.setBorder(b);
        jPasswordField1.setBorder(b);
        //textfieldquestion.setBorder(b);
        textfieldanswer.setBorder(b);
    }//GEN-LAST:event_jPasswordField2KeyTyped

    private void btn_resetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_resetMouseEntered

    }//GEN-LAST:event_btn_resetMouseEntered

    private void btn_resetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_resetMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_resetMouseExited

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        
        textfieldusername.setText(null);
        jPasswordField1.setText(null);
        jPasswordField2.setText(null);
        textfieldquestion.setText(null);
        textfieldanswer.setText(null);
    }//GEN-LAST:event_btn_resetActionPerformed

    private void btn_saveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_saveMouseEntered
        btn_save.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_btn_saveMouseEntered

    private void btn_saveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_saveMouseExited
        btn_save.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_btn_saveMouseExited

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        String username = textfieldusername.getText();
        String question = textfieldquestion.getText();
        String answer =  textfieldanswer.getText();
        String password = String.valueOf(jPasswordField1.getPassword());
        if (verifData()) {
            Connection con = (Connection) myConnection.getConnection();
            PreparedStatement ps;
            ResultSet rs;

            try {
                ps = (PreparedStatement) con.prepareStatement("SELECT * FROM librarianlogin WHERE Username = '" + username + "' and answer = '" + answer + "'");
                //ps.setString(1, jTextField1.getText());
                rs = ps.executeQuery();

                if (rs.next()) {
                    String updateQuery = "UPDATE librarianlogin SET Password='" + password + "' WHERE Username='" + username + "' and answer = '" + answer + "'";
                    ps = (PreparedStatement) con.prepareStatement(updateQuery);
                    //ps.setString(1, jTextField4.getText().trim());
                    //ps.setInt(5, myConnection.index);

                    if (ps.executeUpdate() != 0) {
                        JOptionPane.showMessageDialog(null, "New Password is Updated", "Message", JOptionPane.INFORMATION_MESSAGE);
                        LibrarianLogin sl = new LibrarianLogin();
                        sl.setVisible(true);
                        this.dispose();
                    } else {
                        JOptionPane.showMessageDialog(null, "Something is wrong", "Message", JOptionPane.ERROR_MESSAGE);

                    }

                } else {
                    JOptionPane.showMessageDialog(null, "Incorrect Answer!");
                }
            } catch (SQLException ex) {
                Logger.getLogger(LibrarianForgotPassword.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btn_saveActionPerformed

    private void textfieldanswerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textfieldanswerMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldanswerMouseClicked

    private void textfieldanswerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textfieldanswerMousePressed
        Border a = BorderFactory.createLineBorder(new Color(64, 134, 176), 2);
        textfieldanswer.setBorder(a);
        Border b = BorderFactory.createLineBorder(new Color(93, 70, 56), 1);
        
        textfieldusername.setBorder(b);
        jPasswordField1.setBorder(b);
        jPasswordField2.setBorder(b);
        //textfieldquestion.setBorder(b);
        
    }//GEN-LAST:event_textfieldanswerMousePressed

    private void textfieldanswerKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textfieldanswerKeyTyped
        Border a = BorderFactory.createLineBorder(new Color(64, 134, 176), 2);
        textfieldanswer.setBorder(a);
        Border b = BorderFactory.createLineBorder(new Color(93, 70, 56), 1);
        
        textfieldusername.setBorder(b);
        jPasswordField1.setBorder(b);
        jPasswordField2.setBorder(b);
        //textfieldquestion.setBorder(b);
    }//GEN-LAST:event_textfieldanswerKeyTyped

    private void textfieldusernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textfieldusernameKeyReleased
         lbl_u.setVisible(false);

        if (textfieldusername.getText().equals("")) {
            lbl_u.setVisible(true);
        }
    }//GEN-LAST:event_textfieldusernameKeyReleased

    private void jPasswordField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyReleased
         lbl_p.setVisible(false);

        if (jPasswordField1.getText().equals("")) {
            lbl_p.setVisible(true);
        }
    }//GEN-LAST:event_jPasswordField1KeyReleased

    private void jPasswordField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField2KeyReleased
        lbl_cp.setVisible(false);

        if (jPasswordField2.getText().equals("")) {
            lbl_cp.setVisible(true);
        }
    }//GEN-LAST:event_jPasswordField2KeyReleased

    private void textfieldanswerKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textfieldanswerKeyReleased
        lbl_a.setVisible(false);

        if (textfieldanswer.getText().equals("")) {
            lbl_a.setVisible(true);
        }
    }//GEN-LAST:event_textfieldanswerKeyReleased

    private void btn_searchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_searchMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_searchMouseEntered

    private void btn_searchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_searchMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_searchMouseExited

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
        String username = textfieldusername.getText();

        Connection con = (Connection) myConnection.getConnection();
        PreparedStatement ps;
        ResultSet rs;

        try {
            ps = (PreparedStatement) con.prepareStatement("SELECT question FROM librarianlogin WHERE username = '" + username + "'");
            //ps.setString(1, jTextField1.getText());
            rs = ps.executeQuery();

            if (rs.next()) {
                textfieldquestion.setText(rs.getString(1));
            } else {
                JOptionPane.showMessageDialog(null, "Username does not exists!");
            }
        } catch (SQLException ex) {
            Logger.getLogger(LibrarianForgotPassword.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_searchActionPerformed

    public boolean isUsernameExist(String un) {
        boolean uExist = false;
        Connection con = (Connection) myConnection.getConnection();
        PreparedStatement ps;
        ResultSet rs;

        try {
            ps = (PreparedStatement) con.prepareStatement("SELECT * FROM registration WHERE username=?");
            ps.setString(1, textfieldusername.getText());

            rs = ps.executeQuery();

            if (rs.next()) {
                uExist = true;

            }
        } catch (SQLException ex) {
            Logger.getLogger(StudentLogin.class.getName()).log(Level.SEVERE, null, ex);
        }

        return uExist;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LibrarianForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LibrarianForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LibrarianForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LibrarianForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LibrarianForgotPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private button.MyButton btn_reset;
    private button.MyButton btn_save;
    private button.MyButton btn_search;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelLogin;
    private javax.swing.JLabel jLabelLoida;
    private javax.swing.JLabel jLabelicon;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JLabel lbl_a;
    private javax.swing.JLabel lbl_cp;
    private javax.swing.JLabel lbl_p;
    private javax.swing.JLabel lbl_u;
    private javax.swing.JLabel lblconfirmpass;
    private javax.swing.JLabel lblconfirmpass1;
    private javax.swing.JLabel lblpassword;
    private javax.swing.JLabel lblpassword1;
    private javax.swing.JLabel lblusername;
    private javax.swing.JTextField textfieldanswer;
    private javax.swing.JLabel textfieldquestion;
    private javax.swing.JTextField textfieldusername;
    // End of variables declaration//GEN-END:variables
}
