/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package librarymanagementkiosk;

import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/**
 *
 * @author CLARISSE
 */
public class Registration extends javax.swing.JFrame {

    /**
     * Creates new form Registration
     */
    public Registration() {
        initComponents();
        this.setLocationRelativeTo(null); //center screen

        Border emptyBorder = BorderFactory.createEmptyBorder();
        btn_register.setBorder(emptyBorder);
        btn_reset.setBorder(emptyBorder);

        btn_register.setFocusPainted(false);
        btn_reset.setFocusPainted(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblfirstname = new javax.swing.JLabel();
        textfieldfirstname = new javax.swing.JTextField();
        textfieldlastname = new javax.swing.JTextField();
        lbllastname = new javax.swing.JLabel();
        lblusername = new javax.swing.JLabel();
        textfieldusername = new javax.swing.JTextField();
        lblpassword = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        lblconfirmpass = new javax.swing.JLabel();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabelLogin = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelicon = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        back = new javax.swing.JLabel();
        jLabelLoida = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        textfieldlrn = new javax.swing.JTextField();
        lbllrn = new javax.swing.JLabel();
        lblpassword1 = new javax.swing.JLabel();
        lblconfirmpass1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btn_reset = new button.MyButton();
        btn_register = new button.MyButton();
        jLabel5 = new javax.swing.JLabel();
        lbl_f = new javax.swing.JLabel();
        lbl_l = new javax.swing.JLabel();
        lbl_lrn = new javax.swing.JLabel();
        lbl_u = new javax.swing.JLabel();
        lbl_p = new javax.swing.JLabel();
        lbl_cp = new javax.swing.JLabel();
        lbl_a = new javax.swing.JLabel();
        textfieldanswer = new javax.swing.JTextField();
        textfieldquestion = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(93, 70, 56), 5));

        lblfirstname.setFont(new java.awt.Font("Rockwell Condensed", 1, 18)); // NOI18N
        lblfirstname.setText("First Name:");

        textfieldfirstname.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        textfieldfirstname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(93, 70, 56)));
        textfieldfirstname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textfieldfirstnameMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                textfieldfirstnameMousePressed(evt);
            }
        });
        textfieldfirstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldfirstnameActionPerformed(evt);
            }
        });
        textfieldfirstname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textfieldfirstnameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textfieldfirstnameKeyTyped(evt);
            }
        });

        textfieldlastname.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        textfieldlastname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(93, 70, 56)));
        textfieldlastname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textfieldlastnameMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                textfieldlastnameMousePressed(evt);
            }
        });
        textfieldlastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldlastnameActionPerformed(evt);
            }
        });
        textfieldlastname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textfieldlastnameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textfieldlastnameKeyTyped(evt);
            }
        });

        lbllastname.setFont(new java.awt.Font("Rockwell Condensed", 1, 18)); // NOI18N
        lbllastname.setText("Last Name:");

        lblusername.setFont(new java.awt.Font("Rockwell Condensed", 1, 18)); // NOI18N
        lblusername.setText("Username:");

        textfieldusername.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        textfieldusername.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(93, 70, 56)));
        textfieldusername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textfieldusernameMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                textfieldusernameMousePressed(evt);
            }
        });
        textfieldusername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textfieldusernameKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textfieldusernameKeyTyped(evt);
            }
        });

        lblpassword.setFont(new java.awt.Font("Rockwell Condensed", 1, 18)); // NOI18N
        lblpassword.setText("Password:");

        jPasswordField1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPasswordField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(93, 70, 56)));
        jPasswordField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordField1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPasswordField1MousePressed(evt);
            }
        });
        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyTyped(evt);
            }
        });

        lblconfirmpass.setFont(new java.awt.Font("Rockwell Condensed", 1, 18)); // NOI18N
        lblconfirmpass.setText("Confirm Password:");

        jPasswordField2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPasswordField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(93, 70, 56)));
        jPasswordField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordField2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPasswordField2MousePressed(evt);
            }
        });
        jPasswordField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField2ActionPerformed(evt);
            }
        });
        jPasswordField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPasswordField2KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPasswordField2KeyTyped(evt);
            }
        });

        jLabelLogin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelLogin.setForeground(new java.awt.Color(12, 105, 169));
        jLabelLogin.setText("Sign in");
        jLabelLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLoginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelLoginMouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Already have an account?");

        jPanel2.setBackground(new java.awt.Color(64, 134, 176));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jLabelicon, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 287, -1, -1));
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 287, -1, -1));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymanagementkiosk/neweralogo.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 180, 173, -1));

        jPanel3.setBackground(new java.awt.Color(64, 134, 176));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymanagementkiosk/icons8-back-arrow-40.png"))); // NOI18N
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                backMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(700, 700, 700)
                .addComponent(back)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(back)
                .addGap(381, 381, 381))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        jLabelLoida.setFont(new java.awt.Font("Rockwell", 1, 36)); // NOI18N
        jLabelLoida.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLoida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymanagementkiosk/era2.png"))); // NOI18N
        jPanel2.add(jLabelLoida, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 360, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Library Management Kiosk ");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 390, -1, -1));

        jPanel21.setBackground(new java.awt.Color(151, 205, 205));
        jPanel21.setPreferredSize(new java.awt.Dimension(500, 25));

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        textfieldlrn.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        textfieldlrn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(93, 70, 56)));
        textfieldlrn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textfieldlrnMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                textfieldlrnMousePressed(evt);
            }
        });
        textfieldlrn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfieldlrnActionPerformed(evt);
            }
        });
        textfieldlrn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textfieldlrnKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textfieldlrnKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textfieldlrnKeyTyped(evt);
            }
        });

        lbllrn.setFont(new java.awt.Font("Rockwell Condensed", 1, 18)); // NOI18N
        lbllrn.setText("LRN:");

        lblpassword1.setFont(new java.awt.Font("Rockwell Condensed", 1, 18)); // NOI18N
        lblpassword1.setText("Security Question:");

        lblconfirmpass1.setFont(new java.awt.Font("Rockwell Condensed", 1, 18)); // NOI18N
        lblconfirmpass1.setText("Answer:");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymanagementkiosk/signup.png"))); // NOI18N

        btn_reset.setForeground(new java.awt.Color(255, 255, 255));
        btn_reset.setText("RESET");
        btn_reset.setBorderColor(new java.awt.Color(64, 134, 176));
        btn_reset.setColor(new java.awt.Color(64, 134, 176));
        btn_reset.setColorClick(new java.awt.Color(102, 153, 255));
        btn_reset.setColorOver(new java.awt.Color(64, 134, 176));
        btn_reset.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_reset.setRadius(30);
        btn_reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_resetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_resetMouseExited(evt);
            }
        });
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });

        btn_register.setText("REGISTER");
        btn_register.setBorderColor(new java.awt.Color(64, 134, 176));
        btn_register.setColorClick(new java.awt.Color(102, 153, 255));
        btn_register.setColorOver(new java.awt.Color(64, 134, 176));
        btn_register.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_register.setRadius(30);
        btn_register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_registerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_registerMouseExited(evt);
            }
        });
        btn_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registerActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymanagementkiosk/cca.png"))); // NOI18N

        lbl_f.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_f.setForeground(new java.awt.Color(255, 0, 0));
        lbl_f.setText("*");

        lbl_l.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_l.setForeground(new java.awt.Color(255, 0, 0));
        lbl_l.setText("*");

        lbl_lrn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_lrn.setForeground(new java.awt.Color(255, 0, 0));
        lbl_lrn.setText("*");

        lbl_u.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_u.setForeground(new java.awt.Color(255, 0, 0));
        lbl_u.setText("*");

        lbl_p.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_p.setForeground(new java.awt.Color(255, 0, 0));
        lbl_p.setText("*");

        lbl_cp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_cp.setForeground(new java.awt.Color(255, 0, 0));
        lbl_cp.setText("*");

        lbl_a.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbl_a.setForeground(new java.awt.Color(255, 0, 0));
        lbl_a.setText("*");

        textfieldanswer.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        textfieldanswer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(93, 70, 56)));
        textfieldanswer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textfieldanswerMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                textfieldanswerMousePressed(evt);
            }
        });
        textfieldanswer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textfieldanswerKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textfieldanswerKeyTyped(evt);
            }
        });

        textfieldquestion.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        textfieldquestion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "What is your mother's maiden name?", "What was the name of your first pet?", "What is the first name of your oldest cousin?", "What was the first thing you learned to cook?", "What is the last name of your favorite elementary school teacher?" }));
        textfieldquestion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textfieldquestionKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelLogin))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textfieldanswer)
                            .addComponent(textfieldquestion, 0, 0, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbllrn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_lrn))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblusername)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_u))
                            .addComponent(lblpassword1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblconfirmpass1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_a))
                            .addComponent(btn_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(244, 244, 244)
                                .addComponent(btn_register, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblpassword)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbl_p))
                                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblconfirmpass)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbl_cp))
                                    .addComponent(jPasswordField2)))
                            .addComponent(textfieldusername)
                            .addComponent(textfieldlrn)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblfirstname)
                                        .addGap(4, 4, 4)
                                        .addComponent(lbl_f))
                                    .addComponent(textfieldfirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textfieldlastname, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(lbllastname)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbl_l)))))))
                .addContainerGap(45, Short.MAX_VALUE))
            .addComponent(jPanel21, javax.swing.GroupLayout.DEFAULT_SIZE, 716, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jLabel5))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblfirstname)
                            .addComponent(lbllastname)
                            .addComponent(lbl_f)
                            .addComponent(lbl_l))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textfieldfirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textfieldlastname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbllrn)
                            .addComponent(lbl_lrn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textfieldlrn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblusername)
                            .addComponent(lbl_u))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textfieldusername, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblconfirmpass)
                                .addComponent(lbl_cp))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblpassword)
                                .addComponent(lbl_p)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblpassword1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textfieldquestion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblconfirmpass1)
                            .addComponent(lbl_a))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(textfieldanswer, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_register, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelLogin)
                            .addComponent(jLabel1))
                        .addGap(0, 8, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public boolean verifData() {
        if (textfieldfirstname.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "First name is required", "Message", JOptionPane.ERROR_MESSAGE);
        } else if (textfieldlastname.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Last name is required", "Message", JOptionPane.ERROR_MESSAGE);
        } else if (textfieldlrn.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "LRN is required", "Message", JOptionPane.ERROR_MESSAGE);
        } else if (textfieldusername.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Username is required", "Message", JOptionPane.ERROR_MESSAGE);
        } else if (jPasswordField1.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Password is required", "Message", JOptionPane.ERROR_MESSAGE);
        } else if (!String.valueOf(jPasswordField1.getPassword()).equals(String.valueOf(jPasswordField2.getPassword()))) {
            JOptionPane.showMessageDialog(null, "Password does not match", "Message", JOptionPane.ERROR_MESSAGE);
        } else if (textfieldquestion.getSelectedItem().toString().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Security Question is required", "Message", JOptionPane.ERROR_MESSAGE);
        } else if (textfieldanswer.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Answer is required", "Message", JOptionPane.ERROR_MESSAGE);
            return false;
        } else {
            return true;
        }
        return false;
    }


    private void textfieldfirstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldfirstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldfirstnameActionPerformed

    private void textfieldlastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldlastnameActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldlastnameActionPerformed

    private void jLabelLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLoginMouseClicked
        StudentLogin log = new StudentLogin();
        log.setVisible(true);
        log.pack();
        log.setLocationRelativeTo(null);
        log.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabelLoginMouseClicked

    private void jPasswordField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField2ActionPerformed

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        Users user = new Users();
        user.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_backMouseClicked

    private void backMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseEntered
        jPanel3.setBackground(new Color(7, 74, 114));
    }//GEN-LAST:event_backMouseEntered

    private void backMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseExited
        jPanel3.setBackground(new Color(64, 134, 176));
    }//GEN-LAST:event_backMouseExited

    private void jLabelLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLoginMouseEntered
        jLabelLogin.setForeground(new Color(8, 14, 112));
    }//GEN-LAST:event_jLabelLoginMouseEntered

    private void jLabelLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLoginMouseExited
        jLabelLogin.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_jLabelLoginMouseExited

    private void textfieldfirstnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textfieldfirstnameMouseClicked

    }//GEN-LAST:event_textfieldfirstnameMouseClicked

    private void textfieldlastnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textfieldlastnameMouseClicked

    }//GEN-LAST:event_textfieldlastnameMouseClicked

    private void textfieldusernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textfieldusernameMouseClicked

    }//GEN-LAST:event_textfieldusernameMouseClicked

    private void jPasswordField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField1MouseClicked

    }//GEN-LAST:event_jPasswordField1MouseClicked

    private void jPasswordField2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField2MouseClicked

    }//GEN-LAST:event_jPasswordField2MouseClicked

    private void textfieldlrnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textfieldlrnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldlrnMouseClicked

    private void textfieldlrnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textfieldlrnMousePressed
        Border a = BorderFactory.createLineBorder(new Color(64, 134, 176), 2);
        textfieldlrn.setBorder(a);
        Border b = BorderFactory.createLineBorder(new Color(93, 70, 56), 1);
        textfieldfirstname.setBorder(b);
        textfieldlastname.setBorder(b);
        textfieldusername.setBorder(b);
        jPasswordField1.setBorder(b);
        jPasswordField2.setBorder(b);
        textfieldquestion.setBorder(b);
        textfieldanswer.setBorder(b);
    }//GEN-LAST:event_textfieldlrnMousePressed

    private void textfieldfirstnameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textfieldfirstnameMousePressed
        Border a = BorderFactory.createLineBorder(new Color(64, 134, 176), 2);
        textfieldfirstname.setBorder(a);
        Border b = BorderFactory.createLineBorder(new Color(93, 70, 56), 1);
        textfieldlrn.setBorder(b);
        textfieldlastname.setBorder(b);
        textfieldusername.setBorder(b);
        jPasswordField1.setBorder(b);
        jPasswordField2.setBorder(b);
        textfieldquestion.setBorder(b);
        textfieldanswer.setBorder(b);
    }//GEN-LAST:event_textfieldfirstnameMousePressed

    private void textfieldlastnameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textfieldlastnameMousePressed
        Border a = BorderFactory.createLineBorder(new Color(64, 134, 176), 2);
        textfieldlastname.setBorder(a);
        Border b = BorderFactory.createLineBorder(new Color(93, 70, 56), 1);
        textfieldfirstname.setBorder(b);
        textfieldlrn.setBorder(b);
        textfieldusername.setBorder(b);
        jPasswordField1.setBorder(b);
        jPasswordField2.setBorder(b);
        textfieldquestion.setBorder(b);
        textfieldanswer.setBorder(b);
    }//GEN-LAST:event_textfieldlastnameMousePressed

    private void textfieldusernameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textfieldusernameMousePressed
        Border a = BorderFactory.createLineBorder(new Color(64, 134, 176), 2);
        textfieldusername.setBorder(a);
        Border b = BorderFactory.createLineBorder(new Color(93, 70, 56), 1);
        textfieldfirstname.setBorder(b);
        textfieldlastname.setBorder(b);
        textfieldlrn.setBorder(b);
        jPasswordField1.setBorder(b);
        jPasswordField2.setBorder(b);
        textfieldquestion.setBorder(b);
        textfieldanswer.setBorder(b);
    }//GEN-LAST:event_textfieldusernameMousePressed

    private void jPasswordField1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField1MousePressed
        Border a = BorderFactory.createLineBorder(new Color(64, 134, 176), 2);
        jPasswordField1.setBorder(a);
        Border b = BorderFactory.createLineBorder(new Color(93, 70, 56), 1);
        textfieldfirstname.setBorder(b);
        textfieldlastname.setBorder(b);
        textfieldlrn.setBorder(b);
        textfieldusername.setBorder(b);
        jPasswordField2.setBorder(b);
        textfieldquestion.setBorder(b);
        textfieldanswer.setBorder(b);
    }//GEN-LAST:event_jPasswordField1MousePressed

    private void jPasswordField2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField2MousePressed
        Border a = BorderFactory.createLineBorder(new Color(64, 134, 176), 2);
        jPasswordField2.setBorder(a);
        Border b = BorderFactory.createLineBorder(new Color(93, 70, 56), 1);
        textfieldfirstname.setBorder(b);
        textfieldlastname.setBorder(b);
        textfieldlrn.setBorder(b);
        textfieldusername.setBorder(b);
        jPasswordField1.setBorder(b);
        textfieldquestion.setBorder(b);
        textfieldanswer.setBorder(b);
    }//GEN-LAST:event_jPasswordField2MousePressed

    private void textfieldfirstnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textfieldfirstnameKeyTyped
        Border a = BorderFactory.createLineBorder(new Color(64, 134, 176), 2);
        textfieldfirstname.setBorder(a);
        Border b = BorderFactory.createLineBorder(new Color(93, 70, 56), 1);
        textfieldlrn.setBorder(b);
        textfieldlastname.setBorder(b);
        textfieldusername.setBorder(b);
        jPasswordField1.setBorder(b);
        jPasswordField2.setBorder(b);
        textfieldquestion.setBorder(b);
        textfieldanswer.setBorder(b);
    }//GEN-LAST:event_textfieldfirstnameKeyTyped

    private void textfieldlastnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textfieldlastnameKeyTyped
        Border a = BorderFactory.createLineBorder(new Color(64, 134, 176), 2);
        textfieldlastname.setBorder(a);
        Border b = BorderFactory.createLineBorder(new Color(93, 70, 56), 1);
        textfieldfirstname.setBorder(b);
        textfieldlrn.setBorder(b);
        textfieldusername.setBorder(b);
        jPasswordField1.setBorder(b);
        jPasswordField2.setBorder(b);
    }//GEN-LAST:event_textfieldlastnameKeyTyped

    private void textfieldlrnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textfieldlrnKeyTyped
        Border a = BorderFactory.createLineBorder(new Color(64, 134, 176), 2);
        textfieldlrn.setBorder(a);
        Border b = BorderFactory.createLineBorder(new Color(93, 70, 56), 1);
        textfieldfirstname.setBorder(b);
        textfieldlastname.setBorder(b);
        textfieldusername.setBorder(b);
        jPasswordField1.setBorder(b);
        jPasswordField2.setBorder(b);
    }//GEN-LAST:event_textfieldlrnKeyTyped

    private void textfieldusernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textfieldusernameKeyTyped
        Border a = BorderFactory.createLineBorder(new Color(64, 134, 176), 2);
        textfieldusername.setBorder(a);
        Border b = BorderFactory.createLineBorder(new Color(93, 70, 56), 1);
        textfieldfirstname.setBorder(b);
        textfieldlastname.setBorder(b);
        textfieldlrn.setBorder(b);
        jPasswordField1.setBorder(b);
        jPasswordField2.setBorder(b);
        textfieldquestion.setBorder(b);
        textfieldanswer.setBorder(b);
    }//GEN-LAST:event_textfieldusernameKeyTyped

    private void jPasswordField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyTyped
        Border a = BorderFactory.createLineBorder(new Color(64, 134, 176), 2);
        jPasswordField1.setBorder(a);
        Border b = BorderFactory.createLineBorder(new Color(93, 70, 56), 1);
        textfieldfirstname.setBorder(b);
        textfieldlastname.setBorder(b);
        textfieldlrn.setBorder(b);
        textfieldusername.setBorder(b);
        jPasswordField2.setBorder(b);
        textfieldquestion.setBorder(b);
        textfieldanswer.setBorder(b);
    }//GEN-LAST:event_jPasswordField1KeyTyped

    private void jPasswordField2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField2KeyTyped
        Border a = BorderFactory.createLineBorder(new Color(64, 134, 176), 2);
        jPasswordField2.setBorder(a);
        Border b = BorderFactory.createLineBorder(new Color(93, 70, 56), 1);
        textfieldfirstname.setBorder(b);
        textfieldlastname.setBorder(b);
        textfieldlrn.setBorder(b);
        textfieldusername.setBorder(b);
        jPasswordField1.setBorder(b);
        textfieldquestion.setBorder(b);
        textfieldanswer.setBorder(b);
    }//GEN-LAST:event_jPasswordField2KeyTyped

    private void textfieldlrnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textfieldlrnKeyPressed
        String lrn = textfieldlrn.getText();
        int length = lrn.length();
        char c = evt.getKeyChar();

        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9') {
            if (length < 12) {
                textfieldlrn.setEditable(true);
            } else {
                textfieldlrn.setEditable(false);
            }
        } else {
            if (evt.getExtendedKeyCode() == KeyEvent.VK_BACKSPACE || evt.getExtendedKeyCode() == KeyEvent.VK_DELETE) {
                textfieldlrn.setEditable(true);
            } else {
                textfieldlrn.setEditable(false);
            }
        }
    }//GEN-LAST:event_textfieldlrnKeyPressed

    private void btn_resetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_resetMouseEntered

    }//GEN-LAST:event_btn_resetMouseEntered

    private void btn_resetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_resetMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_resetMouseExited

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        textfieldfirstname.setText(null);
        textfieldlastname.setText(null);
        textfieldlrn.setText(null);
        textfieldusername.setText(null);
        jPasswordField1.setText(null);
        jPasswordField2.setText(null);
        //textfieldquestion.setSelected(null);
        textfieldanswer.setText(null);
    }//GEN-LAST:event_btn_resetActionPerformed

    private void btn_registerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_registerMouseEntered
        btn_register.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_btn_registerMouseEntered

    private void btn_registerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_registerMouseExited
        btn_register.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_btn_registerMouseExited

    private void btn_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registerActionPerformed
        if (verifData()) {
            Connection con = (Connection) myConnection.getConnection();
            PreparedStatement ps;

            try {
                ps = (PreparedStatement) con.prepareStatement("INSERT INTO registration (first_name,last_name,lrn,username,password,question,answer) VALUES (?,?,?,?,?,?,?)");
                ps.setString(1, textfieldfirstname.getText());
                ps.setString(2, textfieldlastname.getText());
                ps.setString(3, textfieldlrn.getText());
                ps.setString(4, textfieldusername.getText());
                ps.setString(5, String.valueOf(jPasswordField1.getPassword()));
                ps.setString(6, textfieldquestion.getSelectedItem().toString());
                ps.setString(7, textfieldanswer.getText());

                if (isUsernameExist(textfieldusername.getText())) {
                    JOptionPane.showMessageDialog(null, "Username already exists", "Message", JOptionPane.INFORMATION_MESSAGE);
                } else if (isLrnExist(textfieldlrn.getText())) {
                    JOptionPane.showMessageDialog(null, "LRN already exists", "Message", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    if (ps.executeUpdate() != 0) {
                        JOptionPane.showMessageDialog(null, "Registered Successfully!", "Message", JOptionPane.INFORMATION_MESSAGE);
                        StudentLogin sl = new StudentLogin();
                        sl.setVisible(true);
                        this.dispose();
                    } else {
                        JOptionPane.showMessageDialog(null, "Something is wrong", "Message", JOptionPane.ERROR_MESSAGE);
                    }
                    textfieldfirstname.setText(null);
                    textfieldlastname.setText(null);
                    textfieldlrn.setText(null);
                    textfieldusername.setText(null);
                    jPasswordField1.setText(null);
                    jPasswordField2.setText(null);
                    //textfieldquestion.setText(null);
                    textfieldanswer.setText(null);
                }

            } catch (Exception ex) {
                Logger.getLogger(Registration.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btn_registerActionPerformed

    private void textfieldanswerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textfieldanswerMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldanswerMouseClicked

    private void textfieldanswerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textfieldanswerMousePressed
        Border a = BorderFactory.createLineBorder(new Color(64, 134, 176), 2);
        textfieldanswer.setBorder(a);
        Border b = BorderFactory.createLineBorder(new Color(93, 70, 56), 1);
        textfieldfirstname.setBorder(b);
        textfieldlastname.setBorder(b);
        textfieldlrn.setBorder(b);
        textfieldusername.setBorder(b);
        jPasswordField1.setBorder(b);
        jPasswordField2.setBorder(b);
        textfieldquestion.setBorder(b);

    }//GEN-LAST:event_textfieldanswerMousePressed

    private void textfieldanswerKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textfieldanswerKeyTyped
        Border a = BorderFactory.createLineBorder(new Color(64, 134, 176), 2);
        textfieldanswer.setBorder(a);
        Border b = BorderFactory.createLineBorder(new Color(93, 70, 56), 1);
        textfieldfirstname.setBorder(b);
        textfieldlastname.setBorder(b);
        textfieldlrn.setBorder(b);
        textfieldusername.setBorder(b);
        jPasswordField1.setBorder(b);
        jPasswordField2.setBorder(b);
        textfieldquestion.setBorder(b);
    }//GEN-LAST:event_textfieldanswerKeyTyped

    private void textfieldfirstnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textfieldfirstnameKeyReleased
        lbl_f.setVisible(false);

        if (textfieldfirstname.getText().equals("")) {
            lbl_f.setVisible(true);
        }
    }//GEN-LAST:event_textfieldfirstnameKeyReleased

    private void textfieldlastnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textfieldlastnameKeyReleased
        lbl_l.setVisible(false);

        if (textfieldlastname.getText().equals("")) {
            lbl_l.setVisible(true);
        }
    }//GEN-LAST:event_textfieldlastnameKeyReleased

    private void textfieldlrnKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textfieldlrnKeyReleased
        lbl_lrn.setVisible(false);

        if (textfieldlrn.getText().equals("")) {
            lbl_lrn.setVisible(true);
        }
    }//GEN-LAST:event_textfieldlrnKeyReleased

    private void textfieldusernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textfieldusernameKeyReleased
        lbl_u.setVisible(false);

        if (textfieldusername.getText().equals("")) {
            lbl_u.setVisible(true);
        }
    }//GEN-LAST:event_textfieldusernameKeyReleased

    private void jPasswordField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyReleased
        lbl_p.setVisible(false);

        if (jPasswordField1.getText().equals("")) {
            lbl_p.setVisible(true);
        }
    }//GEN-LAST:event_jPasswordField1KeyReleased

    private void jPasswordField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField2KeyReleased
        lbl_cp.setVisible(false);

        if (jPasswordField2.getText().equals("")) {
            lbl_cp.setVisible(true);
        }
    }//GEN-LAST:event_jPasswordField2KeyReleased

    private void textfieldanswerKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textfieldanswerKeyReleased
        lbl_a.setVisible(false);

        if (textfieldanswer.getText().equals("")) {
            lbl_a.setVisible(true);
        }
    }//GEN-LAST:event_textfieldanswerKeyReleased

    private void textfieldquestionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textfieldquestionKeyPressed
        
    }//GEN-LAST:event_textfieldquestionKeyPressed

    private void textfieldlrnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfieldlrnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfieldlrnActionPerformed

    public boolean isUsernameExist(String un) {
        boolean uExist = false;
        Connection con = (Connection) myConnection.getConnection();
        PreparedStatement ps;
        ResultSet rs;

        try {
            ps = (PreparedStatement) con.prepareStatement("SELECT * FROM registration WHERE username=?");
            ps.setString(1, textfieldusername.getText());

            rs = ps.executeQuery();

            if (rs.next()) {
                uExist = true;

            }
        } catch (SQLException ex) {
            Logger.getLogger(StudentLogin.class.getName()).log(Level.SEVERE, null, ex);
        }

        return uExist;
    }
    
    public boolean isLrnExist(String un) {
        boolean lrnExist = false;
        Connection con = (Connection) myConnection.getConnection();
        PreparedStatement ps;
        ResultSet rs;

        try {
            ps = (PreparedStatement) con.prepareStatement("SELECT * FROM registration WHERE lrn=?");
            ps.setString(1, textfieldlrn.getText());

            rs = ps.executeQuery();

            if (rs.next()) {
                lrnExist = true;

            }
        } catch (SQLException ex) {
            Logger.getLogger(StudentLogin.class.getName()).log(Level.SEVERE, null, ex);
        }

        return lrnExist;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private button.MyButton btn_register;
    private button.MyButton btn_reset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelLogin;
    private javax.swing.JLabel jLabelLoida;
    private javax.swing.JLabel jLabelicon;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JLabel lbl_a;
    private javax.swing.JLabel lbl_cp;
    private javax.swing.JLabel lbl_f;
    private javax.swing.JLabel lbl_l;
    private javax.swing.JLabel lbl_lrn;
    private javax.swing.JLabel lbl_p;
    private javax.swing.JLabel lbl_u;
    private javax.swing.JLabel lblconfirmpass;
    private javax.swing.JLabel lblconfirmpass1;
    private javax.swing.JLabel lblfirstname;
    private javax.swing.JLabel lbllastname;
    private javax.swing.JLabel lbllrn;
    private javax.swing.JLabel lblpassword;
    private javax.swing.JLabel lblpassword1;
    private javax.swing.JLabel lblusername;
    private javax.swing.JTextField textfieldanswer;
    private javax.swing.JTextField textfieldfirstname;
    private javax.swing.JTextField textfieldlastname;
    private javax.swing.JTextField textfieldlrn;
    private javax.swing.JComboBox<String> textfieldquestion;
    private javax.swing.JTextField textfieldusername;
    // End of variables declaration//GEN-END:variables
}
